/**
 * Generates src/environments/environment.prod.ts from the API_URL env var.
 *
 * Runs as the `prebuild` step before `ng build`. Netlify (and any other host)
 * can set API_URL via its dashboard so the prod backend URL never has to be
 * committed to the repo.
 *
 * If API_URL is not set the script falls back to localhost so a local
 * `npm run build` still succeeds during development.
 */
const fs = require('fs');
const path = require('path');

const apiUrl = process.env.API_URL || 'http://localhost:5000/api';

const targetPath = path.resolve(__dirname, '..', 'src', 'environments', 'environment.prod.ts');

const content = `// AUTO-GENERATED by scripts/set-env.js. Do not edit manually.
// To change the value, update the API_URL environment variable and rebuild.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}',
};
`;

fs.writeFileSync(targetPath, content, 'utf8');

const source = process.env.API_URL ? 'API_URL env var' : 'localhost fallback';
console.log(`[set-env] wrote ${path.basename(targetPath)} with apiUrl=${apiUrl} (${source})`);
